feat: add forms for login and register
mindenit/nure-schedule-vue pull request #14
Opened 2024-01-18 21:26 UTC by perkinson1251

### Migrated from React project:
- SignIn form;
- SignUp form;

### Errors:
1. `isDisabled` doesn't work, but I don't know why. Code:
```ts
const isDisabled = [emailValue.value, passwordValue.value].some((val) => val === '')
```

2. Submit don't work, but I don't know why. Error screen:
![chrome_MG3UMCelLE](https://github.com/mindenit/nure-schedule-vue/assets/47219330/ea29debe-ca55-4ed7-970c-fa47b757fd45)

2024-01-18 22:04 UTC, OneLiL05 requested changes
Read comment, and resolve issues

2024-01-18 22:04 UTC, OneLiL05 commented on src/core/composables/useSigninForm.ts
> +  const isDisabled = ref([emailValue.value, passwordValue.value].some((val) => val === ''))
I guess, here you need to change `ref` to `computed`, the code will look like this:

```ts
const isDisabled = computed(() => {
  return [emailValue.value, passwordValue.value].some((val) => val === '')
})
```

2024-01-18 22:04 UTC, OneLiL05 commented on src/core/composables/useSigninForm.ts
> +  const handleEmailChange = (e: any) => {
Remove this function since it's useless

2024-01-18 22:04 UTC, OneLiL05 commented on src/core/composables/useSigninForm.ts
> +  const handlePasswordChange = (e: any) => {
Remove this function

2024-01-18 22:04 UTC, OneLiL05 commented on src/core/composables/useSignupForm.ts
> +  const isDisabled = ref([emailValue.value, passwordValue.value].some((val) => val === ''))
Change `ref` to the `computed`

2024-01-18 22:04 UTC, OneLiL05 commented on src/core/composables/useSignupForm.ts
> +  const handleEmailChange = (e: any) => {
Remove this function

2024-01-18 22:04 UTC, OneLiL05 commented on src/core/composables/useSignupForm.ts
> +  const handlePasswordChange = (e: any) => {
Remove this function

2024-01-18 22:04 UTC, OneLiL05 commented on src/components/ui/TextField/TextField.vue
> +const emit = defineEmits(['update:value'])
Change it to the previous version

2024-01-18 22:04 UTC, OneLiL05 commented on src/components/ui/TextField/TextField.vue
> +const model = useVModel(props, 'value', emit)
Change it to the previous version

2024-01-19 10:52 UTC, perkinson1251 commented
New commit has one major bug: buttons `Увійти` and `Зареєструватися` don't work, but I don't know why

2024-01-19 16:41 UTC, OneLiL05 requested changes
There are both `tailwindcss` issues and two unresolved issues from previous review, resolve all of them and pr will be ready to be merged

2024-01-19 16:41 UTC, OneLiL05 commented on src/router/index.ts
> +      component: SignupView
Change to `() => import('../views/SignupView.vue')`

2024-01-19 16:41 UTC, OneLiL05 commented on src/router/index.ts
> +      component: LoginView
Change to `() => import('../views/LoginView.vue')`

2024-01-19 16:41 UTC, OneLiL05 commented on src/layouts/AuthLayout/AuthLayout.vue
> +  @media (min-width: 900px) {
Change to `min-width: theme('screens.md')`

2024-01-20 09:19 UTC, perkinson1251 commented
A new bug has appeared: the theme does not work on the `Login` and `Signup` pages, what I mean is that you can choose a `Dark` theme, but on these pages the theme will be chosen randomly. And the bugs with the `Login` and `Register` buttons are not fixed.

We should meet in Discord today, because I don't really understand how to fix these bugs

2024-01-20 21:36 UTC, OneLiL05 approved these changes

2024-01-20 21:36 UTC, merged