feat: add Card, Title and Loader components
mindenit/nure-schedule-vue pull request #7
Opened 2024-01-16 21:09 UTC by perkinson1251

### Added:
- Loader component
- Card component (all variations)
- Title component (all variations)

2024-01-16 22:43 UTC, OneLiL05 requested changes
Read the comments and resolve issues

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Loader/TheLoader.vue
> +.Spinner {
Re-write `Spinner` class using tailwind

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Card/CardAvatar.vue
> +    class="flex justify-center items-center shrink-0 rounded-[50%] text-center w-[48px] h-[48px]"
Move all these utility classes to some css class, and then just add it to the element, like this:

```vue
<template>
  <div class="YourClass">
    // Your content
  </div>
</template>
<style lang="scss" scoped>
  .YourClass {
    // apply utility classes
  }
<style>
```

Change `w-[48px] h-[48px]` to `size-12`, and `rounded-[50%]` to `rounded-full`

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Card/GroupCard.vue
> +    <div class="w-full flex flex-row flex-nowrap justify-between items-center gap-4">
Move all these utility classes to some css class, and then just add it to the element

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Card/SubjectCard.vue
> +    <div class="flex flex-row flex-nowrap justify-between items-center gap-4">
Move all these utility classes to some css class, and then just add it to the element

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Card/TextSubjectCard.vue
> +  <div class="flex flex-col items-start shrink-0 self-stretch w-full">
Move all these utility classes to some css class, and then just add it to the element

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Loader/TheLoader.vue
> +    class="LoaderContainer fixed top-0 left-0 right-0 bottom-0 flex justify-center items-center z-[999]"
Move all these utility classes to `LoaderContainer`

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Card/TextSubjectCard.vue
> +      <span v-for="item in props.groups ? props.groups : []" :key="item.id">{{ item.name }}</span>
I guess here you can remove ternary by adding default to groups prop, and please change `item` to `group`

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Card/SubjectCard.vue
> +const avatarText: string = props.subjectBrief.slice(0, 2)
Here it would be better to move this to a computed:

```ts
const avatarText = computed(() => {
  return props.subjectBrief.slice(0, 2)
})
```

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Card/SubjectCard.vue
> +      <CardAvatar :letters="`${avatarText}`" :color="`${avatarColor}`" />
Change to `:letters="avatarText"`, and `:color="avatarColor"`

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Card/CardAvatar.vue
> +    :style="{ background: props.color }"
In vue templates instead accessing to prop like this `props.yourProp` you can just access it just by its name. Please re-write all your prop accessing in your templates considering this

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Title/TheTitle.vue
> +    class="font-montserrat Muted text-sm leading-[18px] font-medium tracking-[0.009rem]"
Move all these utility classes to some css class, and then just add it to the element

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Title/TheTitle.vue
> +  <h5 class="font-roboto Muted text-xs font-light" v-if="props.variant === 'light'">
Move all these utility classes to some css class, and then just add it to the element

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Title/TheTitle.vue
> +  <h3
Move all these utility classes to some css class, and then just add it to the element

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Title/TheTitle.vue
> +    class="font-montserrat text-[32px] leading-10 font-extrabold Contrast mb-[10px]"
Move all these utility classes to some css class, and then just add it to the element

2024-01-16 22:43 UTC, OneLiL05 commented on src/core/constants/subjectColors.ts
> +  lecture: '#5086A4',
Change object's fields names to upper case

2024-01-16 22:43 UTC, OneLiL05 commented on src/components/ui/Card/CardAvatar.vue
> +const props = defineProps<Props>()
If you are not using props in `script` tag, you can only keep `defineProps<Props>()`. Example:

```ts
// Before
const props = defineProps<Props>()

// After
defineProps<Props>()
```

2024-01-17 22:56 UTC, OneLiL05 requested changes
Everything looks fine, but there are some issues with tailwindcss, fix them and this pr will be ready to be merged

2024-01-17 22:56 UTC, OneLiL05 commented on src/assets/main.scss
> +    @apply flex flex-col items-start shrink-0 self-stretch border-[1px] border-solid border-outline bg-surface rounded-xl p-4 cursor-pointer w-[350px] duration-200 max-sm:w-full;
Instead of `border-[1px]` use just `border`

2024-01-17 22:56 UTC, OneLiL05 commented on src/components/ui/Card/CardAvatar.vue
> +  @apply flex justify-center items-center shrink-0 rounded-[50%] text-center w-[48px] h-[48px];
Change `w-[48px] h-[48px]` to `size-12`, and `rounded-[50%]` to `rounded-full`

2024-01-17 22:56 UTC, OneLiL05 commented on src/components/ui/Card/InfoCard.vue
> +  @apply text-muted font-montserrat text-lg leading-[20px] font-medium tracking-[0.016rem];
Change `leading-[20px]` to `leading-5`

2024-01-17 22:56 UTC, OneLiL05 commented on src/components/ui/Loader/TheLoader.vue
> +  @apply font-poppins text-[#4a4a4a] font-medium text-[25px] box-content h-[40px] p-[10px] flex rounded-lg;
Change `h-[40px]` to `h-10` and I guess it would be better to change `text-[25px]` to `text-2xl`, since 1px difference doesn't make sense

2024-01-17 22:56 UTC, OneLiL05 commented on src/components/ui/Loader/TheLoader.vue
> +  @apply border-r-primary animate-loader-spin grid w-[56px] h-[56px] border-4 border-solid border-[#0000] rounded-[50%];
Change `border-[#0000]` to `border-black`, `w-[56px] h-[56px]` to `size-14`, `rounded-[50%]` to `rounded-full` and I guess you can remove `border-solid` since it will have solid style by default

2024-01-17 22:56 UTC, OneLiL05 commented on src/components/ui/Loader/TheLoader.vue
> +    @apply content-[""] m-0.5 border-inherit rounded-[50%] animate-[loader-spin_2s_infinite]
Change `rounded-[50%]` to `rounded-full`

2024-01-17 22:56 UTC, OneLiL05 commented on src/components/ui/Title/TheTitle.vue
> +  @apply font-montserrat text-xl leading-[24px] tracking-wide font-bold Contrast;
Change `leading-[24px]` to `leading-6`

2024-01-18 09:15 UTC, perkinson1251 commented on src/components/ui/Loader/TheLoader.vue
> +  @apply border-r-primary animate-loader-spin grid w-[56px] h-[56px] border-4 border-solid border-[#0000] rounded-[50%];
Sorry, I can't change `border-[#0000]` to `border-black` because in other variations this style doesn't work. This part of the loader should be fully transperent, but `border-transperent` gives the wrong result. Removing this property causes styling problems.
P.S: I've pushed new commit

2024-01-18 11:01 UTC, OneLiL05 commented on src/components/ui/Loader/TheLoader.vue
> +  @apply border-r-primary animate-loader-spin grid w-[56px] h-[56px] border-4 border-solid border-[#0000] rounded-[50%];
Ok, I got you

2024-01-18 11:02 UTC, OneLiL05 approved these changes

2024-01-18 11:02 UTC, merged